/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_obi_OpenEBTS */

#ifndef _Included_com_obi_OpenEBTS
#define _Included_com_obi_OpenEBTS
#ifdef __cplusplus
extern "C" {
#endif
#undef com_obi_OpenEBTS_IMAGEFORMAT_RAW
#define com_obi_OpenEBTS_IMAGEFORMAT_RAW 0L
#undef com_obi_OpenEBTS_IMAGEFORMAT_BMP
#define com_obi_OpenEBTS_IMAGEFORMAT_BMP 1L
#undef com_obi_OpenEBTS_IMAGEFORMAT_JPG
#define com_obi_OpenEBTS_IMAGEFORMAT_JPG 2L
#undef com_obi_OpenEBTS_IMAGEFORMAT_WSQ
#define com_obi_OpenEBTS_IMAGEFORMAT_WSQ 3L
#undef com_obi_OpenEBTS_IMAGEFORMAT_JP2
#define com_obi_OpenEBTS_IMAGEFORMAT_JP2 4L
#undef com_obi_OpenEBTS_IMAGEFORMAT_FX4
#define com_obi_OpenEBTS_IMAGEFORMAT_FX4 5L
#undef com_obi_OpenEBTS_IMAGEFORMAT_CBEFF
#define com_obi_OpenEBTS_IMAGEFORMAT_CBEFF 6L
#undef com_obi_OpenEBTS_IMAGEFORMAT_PNG
#define com_obi_OpenEBTS_IMAGEFORMAT_PNG 7L
#undef com_obi_OpenEBTS_IW_SUCCESS
#define com_obi_OpenEBTS_IW_SUCCESS 0L
#undef com_obi_OpenEBTS_IW_ERR_LOADING_VERICATION
#define com_obi_OpenEBTS_IW_ERR_LOADING_VERICATION 1L
#undef com_obi_OpenEBTS_IW_ERR_OPENING_FILE_FOR_READING
#define com_obi_OpenEBTS_IW_ERR_OPENING_FILE_FOR_READING 2L
#undef com_obi_OpenEBTS_IW_ERR_OPENING_FILE_FOR_WRITING
#define com_obi_OpenEBTS_IW_ERR_OPENING_FILE_FOR_WRITING 3L
#undef com_obi_OpenEBTS_IW_ERR_READING_FILE
#define com_obi_OpenEBTS_IW_ERR_READING_FILE 4L
#undef com_obi_OpenEBTS_IW_ERR_WRITING_FILE
#define com_obi_OpenEBTS_IW_ERR_WRITING_FILE 5L
#undef com_obi_OpenEBTS_IW_ERR_RECORD_NOT_FOUND
#define com_obi_OpenEBTS_IW_ERR_RECORD_NOT_FOUND 6L
#undef com_obi_OpenEBTS_IW_ERR_TRANSACTION_NOT_LOADED
#define com_obi_OpenEBTS_IW_ERR_TRANSACTION_NOT_LOADED 7L
#undef com_obi_OpenEBTS_IW_ERR_VERIFICATION_NOT_LOADED
#define com_obi_OpenEBTS_IW_ERR_VERIFICATION_NOT_LOADED 8L
#undef com_obi_OpenEBTS_IW_ERR_NULL_POINTER
#define com_obi_OpenEBTS_IW_ERR_NULL_POINTER 9L
#undef com_obi_OpenEBTS_IW_ERR_NULL_TRANSACTION_POINTER
#define com_obi_OpenEBTS_IW_ERR_NULL_TRANSACTION_POINTER 10L
#undef com_obi_OpenEBTS_IW_ERR_UNSUPPORTED_IMAGE_FORMAT
#define com_obi_OpenEBTS_IW_ERR_UNSUPPORTED_IMAGE_FORMAT 11L
#undef com_obi_OpenEBTS_IW_ERR_UNSUPPORTED_RECORD_TYPE
#define com_obi_OpenEBTS_IW_ERR_UNSUPPORTED_RECORD_TYPE 12L
#undef com_obi_OpenEBTS_IW_ERR_INDEX_OUT_OF_RANGE
#define com_obi_OpenEBTS_IW_ERR_INDEX_OUT_OF_RANGE 13L
#undef com_obi_OpenEBTS_IW_ERR_INVALID_SUBFIELD_NUM
#define com_obi_OpenEBTS_IW_ERR_INVALID_SUBFIELD_NUM 14L
#undef com_obi_OpenEBTS_IW_ERR_MNEMONIC_NOT_FOUND
#define com_obi_OpenEBTS_IW_ERR_MNEMONIC_NOT_FOUND 15L
#undef com_obi_OpenEBTS_IW_ERR_OUT_OF_MEMORY
#define com_obi_OpenEBTS_IW_ERR_OUT_OF_MEMORY 16L
#undef com_obi_OpenEBTS_IW_ERR_WSQ_COMPRESS
#define com_obi_OpenEBTS_IW_ERR_WSQ_COMPRESS 17L
#undef com_obi_OpenEBTS_IW_ERR_WSQ_DECOMPRESS
#define com_obi_OpenEBTS_IW_ERR_WSQ_DECOMPRESS 18L
#undef com_obi_OpenEBTS_IW_ERR_IMAGE_CONVERSION
#define com_obi_OpenEBTS_IW_ERR_IMAGE_CONVERSION 19L
#undef com_obi_OpenEBTS_IW_ERR_HEADER_ITEM
#define com_obi_OpenEBTS_IW_ERR_HEADER_ITEM 20L
#undef com_obi_OpenEBTS_IW_ERR_UNSUPPORTED_BIT_DEPTH
#define com_obi_OpenEBTS_IW_ERR_UNSUPPORTED_BIT_DEPTH 21L
#undef com_obi_OpenEBTS_IW_WARN_TRANSACTION_FAILED_VERIFICATION
#define com_obi_OpenEBTS_IW_WARN_TRANSACTION_FAILED_VERIFICATION 1000L
#undef com_obi_OpenEBTS_IW_WARN_INVALID_FIELD_NUM
#define com_obi_OpenEBTS_IW_WARN_INVALID_FIELD_NUM 1001L
#undef com_obi_OpenEBTS_IW_WARN_REQ_FIELD_MISSING
#define com_obi_OpenEBTS_IW_WARN_REQ_FIELD_MISSING 1002L
#undef com_obi_OpenEBTS_IW_WARN_INCORRECT_ITEM_COUNT
#define com_obi_OpenEBTS_IW_WARN_INCORRECT_ITEM_COUNT 1003L
#undef com_obi_OpenEBTS_IW_WARN_TOO_FEW_DATA_CHARS
#define com_obi_OpenEBTS_IW_WARN_TOO_FEW_DATA_CHARS 1004L
#undef com_obi_OpenEBTS_IW_WARN_TOO_MANY_DATA_CHARS
#define com_obi_OpenEBTS_IW_WARN_TOO_MANY_DATA_CHARS 1005L
#undef com_obi_OpenEBTS_IW_WARN_DATA_NOT_NUMERIC
#define com_obi_OpenEBTS_IW_WARN_DATA_NOT_NUMERIC 1006L
#undef com_obi_OpenEBTS_IW_WARN_DATA_NOT_ALPHA
#define com_obi_OpenEBTS_IW_WARN_DATA_NOT_ALPHA 1007L
#undef com_obi_OpenEBTS_IW_WARN_DATA_NOT_ALPHANUMERIC
#define com_obi_OpenEBTS_IW_WARN_DATA_NOT_ALPHANUMERIC 1008L
#undef com_obi_OpenEBTS_IW_WARN_TOO_FEW_SUBFIELDS
#define com_obi_OpenEBTS_IW_WARN_TOO_FEW_SUBFIELDS 1009L
#undef com_obi_OpenEBTS_IW_WARN_TOO_MANY_SUBFIELDS
#define com_obi_OpenEBTS_IW_WARN_TOO_MANY_SUBFIELDS 1010L
#undef com_obi_OpenEBTS_IW_WARN_UNSUPPORT_FIELD_PRESENT
#define com_obi_OpenEBTS_IW_WARN_UNSUPPORT_FIELD_PRESENT 1011L
#undef com_obi_OpenEBTS_IW_WARN_TRANSACTION_FAILED_XML_PARSE
#define com_obi_OpenEBTS_IW_WARN_TRANSACTION_FAILED_XML_PARSE 1012L
#undef com_obi_OpenEBTS_IW_WARN_DATA_NOT_NUMERIC_SPECIAL
#define com_obi_OpenEBTS_IW_WARN_DATA_NOT_NUMERIC_SPECIAL 1013L
#undef com_obi_OpenEBTS_IW_WARN_DATA_NOT_ALPHA_SPECIAL
#define com_obi_OpenEBTS_IW_WARN_DATA_NOT_ALPHA_SPECIAL 1014L
#undef com_obi_OpenEBTS_IW_WARN_DATA_NOT_ALPHANUMERIC_SPECIAL
#define com_obi_OpenEBTS_IW_WARN_DATA_NOT_ALPHANUMERIC_SPECIAL 1015L
#undef com_obi_OpenEBTS_IW_WARN_INVALID_DATE
#define com_obi_OpenEBTS_IW_WARN_INVALID_DATE 1016L
#undef com_obi_OpenEBTS_IW_WARN_INVALID_DATA
#define com_obi_OpenEBTS_IW_WARN_INVALID_DATA 1017L
#undef com_obi_OpenEBTS_IW_WARN_DATA_NOT_PRINT
#define com_obi_OpenEBTS_IW_WARN_DATA_NOT_PRINT 1018L
#undef com_obi_OpenEBTS_IW_WARN_DATA_NOT_PRINTCTRL
#define com_obi_OpenEBTS_IW_WARN_DATA_NOT_PRINTCTRL 1019L
#undef com_obi_OpenEBTS_IW_WARN_REQ_RECORD_MISSING
#define com_obi_OpenEBTS_IW_WARN_REQ_RECORD_MISSING 1020L
#undef com_obi_OpenEBTS_IW_WARN_UNSUPPORT_RECORD_PRESENT
#define com_obi_OpenEBTS_IW_WARN_UNSUPPORT_RECORD_PRESENT 1021L
#undef com_obi_OpenEBTS_IW_WARN_UNKNOWN_TOT
#define com_obi_OpenEBTS_IW_WARN_UNKNOWN_TOT 1022L
/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWNew
 * Signature: (Ljava/lang/String;Lcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWNew
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWReadFromFile
 * Signature: (Ljava/lang/String;ILcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWReadFromFile
  (JNIEnv *, jobject, jstring, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWWriteToFile
 * Signature: (ILjava/lang/String;Lcom/obi/OpenEBTS/NISTFileFormat;Lcom/obi/OpenEBTS/NISTReturn;)V
 */
JNIEXPORT void JNICALL Java_com_obi_OpenEBTS_IWWriteToFile
  (JNIEnv *, jobject, jint, jstring, jobject, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWClose
 * Signature: (ILcom/obi/OpenEBTS/NISTReturn;)V
 */
JNIEXPORT void JNICALL Java_com_obi_OpenEBTS_IWClose
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWAddRecord
 * Signature: (IILcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWAddRecord
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWDeleteRecord
 * Signature: (IIILcom/obi/OpenEBTS/NISTReturn;)V
 */
JNIEXPORT void JNICALL Java_com_obi_OpenEBTS_IWDeleteRecord
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetRecordTypeCount
 * Signature: (IILcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWGetRecordTypeCount
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetNumRecords
 * Signature: (ILcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWGetNumRecords
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWSetDataViaMnemonic
 * Signature: (ILjava/lang/String;IILjava/lang/String;Lcom/obi/OpenEBTS/NISTReturn;)V
 */
JNIEXPORT void JNICALL Java_com_obi_OpenEBTS_IWSetDataViaMnemonic
  (JNIEnv *, jobject, jint, jstring, jint, jint, jstring, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetDataViaMnemonic
 * Signature: (ILjava/lang/String;IILcom/obi/OpenEBTS/NISTReturn;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_obi_OpenEBTS_IWGetDataViaMnemonic
  (JNIEnv *, jobject, jint, jstring, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWSetImage
 * Signature: (III[BIIILcom/obi/OpenEBTS/NISTReturn;)V
 */
JNIEXPORT void JNICALL Java_com_obi_OpenEBTS_IWSetImage
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jint, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetImage
 * Signature: (IIILcom/obi/OpenEBTS/NISTReturn;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_obi_OpenEBTS_IWGetImage
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetImageFormat
 * Signature: (IIILcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWGetImageFormat
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetImageWidth
 * Signature: (IIILcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWGetImageWidth
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetImageHeight
 * Signature: (IIILcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWGetImageHeight
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetImageDepth
 * Signature: (IIILcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWGetImageDepth
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWSetImageFromFile
 * Signature: (IIILjava/lang/String;IIILcom/obi/OpenEBTS/NISTReturn;)V
 */
JNIEXPORT void JNICALL Java_com_obi_OpenEBTS_IWSetImageFromFile
  (JNIEnv *, jobject, jint, jint, jint, jstring, jint, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetImageAs
 * Signature: (IIIILcom/obi/OpenEBTS/NISTReturn;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_obi_OpenEBTS_IWGetImageAs
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetImageAsToFile
 * Signature: (IIILjava/lang/String;ILcom/obi/OpenEBTS/NISTReturn;)V
 */
JNIEXPORT void JNICALL Java_com_obi_OpenEBTS_IWGetImageAsToFile
  (JNIEnv *, jobject, jint, jint, jint, jstring, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWReadVerification
 * Signature: (Ljava/lang/String;Ljava/lang/StringBuffer;Lcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWReadVerification
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWCloseVerification
 * Signature: (ILcom/obi/OpenEBTS/NISTReturn;)V
 */
JNIEXPORT void JNICALL Java_com_obi_OpenEBTS_IWCloseVerification
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWSetVerification
 * Signature: (IILcom/obi/OpenEBTS/NISTReturn;)V
 */
JNIEXPORT void JNICALL Java_com_obi_OpenEBTS_IWSetVerification
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWVerify
 * Signature: (ILcom/obi/OpenEBTS/NISTReturn;)V
 */
JNIEXPORT void JNICALL Java_com_obi_OpenEBTS_IWVerify
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetErrorCount
 * Signature: (ILcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWGetErrorCount
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetErrorString
 * Signature: (IILcom/obi/OpenEBTS/NISTReturn;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_obi_OpenEBTS_IWGetErrorString
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetErrorCode
 * Signature: (IILcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWGetErrorCode
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetFieldCount
 * Signature: (IIILcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWGetFieldCount
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetNextField
 * Signature: (IIIILcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWGetNextField
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWNumSubfields
 * Signature: (IIIILcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWNumSubfields
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWNumItems
 * Signature: (IIIIILcom/obi/OpenEBTS/NISTReturn;)I
 */
JNIEXPORT jint JNICALL Java_com_obi_OpenEBTS_IWNumItems
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWFindItem
 * Signature: (IIIIIILcom/obi/OpenEBTS/NISTReturn;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_obi_OpenEBTS_IWFindItem
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWSetItem
 * Signature: (ILjava/lang/String;IIIIILcom/obi/OpenEBTS/NISTReturn;)V
 */
JNIEXPORT void JNICALL Java_com_obi_OpenEBTS_IWSetItem
  (JNIEnv *, jobject, jint, jstring, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetTransactionCategories
 * Signature: (ILcom/obi/OpenEBTS/NISTReturn;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_obi_OpenEBTS_IWGetTransactionCategories
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetTransactionTypeNames
 * Signature: (ILjava/lang/String;Lcom/obi/OpenEBTS/NISTReturn;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_obi_OpenEBTS_IWGetTransactionTypeNames
  (JNIEnv *, jobject, jint, jstring, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetTransactionTypeDescriptions
 * Signature: (ILjava/lang/String;Lcom/obi/OpenEBTS/NISTReturn;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_obi_OpenEBTS_IWGetTransactionTypeDescriptions
  (JNIEnv *, jobject, jint, jstring, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetRecordTypeOccurrences
 * Signature: (ILjava/lang/String;Lcom/obi/OpenEBTS/NISTReturn;)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_obi_OpenEBTS_IWGetRecordTypeOccurrences
  (JNIEnv *, jobject, jint, jstring, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetMnemonicsNames
 * Signature: (ILjava/lang/String;Lcom/obi/OpenEBTS/NISTReturn;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_obi_OpenEBTS_IWGetMnemonicsNames
  (JNIEnv *, jobject, jint, jstring, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetMnemonicsDescriptions
 * Signature: (ILjava/lang/String;Lcom/obi/OpenEBTS/NISTReturn;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_obi_OpenEBTS_IWGetMnemonicsDescriptions
  (JNIEnv *, jobject, jint, jstring, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetRuleRestrictions
 * Signature: (ILjava/lang/String;Ljava/lang/String;Lcom/obi/OpenEBTS/NISTReturn;)Lcom/obi/OpenEBTS/NISTFieldRules;
 */
JNIEXPORT jobject JNICALL Java_com_obi_OpenEBTS_IWGetRuleRestrictions
  (JNIEnv *, jobject, jint, jstring, jstring, jobject);

/*
 * Class:     com_obi_OpenEBTS
 * Method:    IWGetValueList
 * Signature: (ILjava/lang/String;Ljava/lang/String;Lcom/obi/OpenEBTS/NISTReturn;)Lcom/obi/OpenEBTS/NISTValueList;
 */
JNIEXPORT jobject JNICALL Java_com_obi_OpenEBTS_IWGetValueList
  (JNIEnv *, jobject, jint, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
